<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Jadwal_rapat_model extends CI_Model
{

    public $table = 'jadwal_rapat';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        //$this->datatables->select('id,id_ruang,id_pengguna,tgl_usul,tgl_mulai,tgl_selesai,judul_rapat,deskripsi_rapat,pimpinan_rapat,peserta_rapat,kontak_person,file_permohonan,status');
        $this->datatables->select('id,tgl_mulai,tgl_selesai,judul_rapat,no_telp,status');
        $this->datatables->from('jadwal_rapat');
        //add this line for join
        //$this->datatables->join('table2', 'jadwal_rapat.field = table2.field');
        //$this->datatables->join('ruangan','jadwal_rapat.id_ruang = ruangan.id_ruangan');
        $this->datatables->join('users','jadwal_rapat.id_pengguna = users.id_pengguna');
        $this->datatables->add_column('action', anchor(site_url('rapat/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))."
            ".anchor(site_url('rapat/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))."
                ".anchor(site_url('rapat/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	//$this->db->or_like('id_ruang', $q);
	//$this->db->or_like('id_pengguna', $q);
	//$this->db->or_like('tgl_usul', $q);
	$this->db->or_like('tgl_mulai', $q);
	$this->db->or_like('tgl_selesai', $q);
	$this->db->or_like('judul_rapat', $q);
	//$this->db->or_like('deskripsi_rapat', $q);
	//$this->db->or_like('pimpinan_rapat', $q);
	//$this->db->or_like('peserta_rapat', $q);
	$this->db->or_like('kontak_person', $q);
	//$this->db->or_like('file_permohonan', $q);
	$this->db->or_like('status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	//$this->db->or_like('id_ruang', $q);
	//$this->db->or_like('id_pengguna', $q);
	//$this->db->or_like('tgl_usul', $q);
	$this->db->or_like('tgl_mulai', $q);
	$this->db->or_like('tgl_selesai', $q);
	$this->db->or_like('judul_rapat', $q);
	//$this->db->or_like('deskripsi_rapat', $q);
	//$this->db->or_like('pimpinan_rapat', $q);
	//$this->db->or_like('peserta_rapat', $q);
	$this->db->or_like('kontak_person', $q);
	//$this->db->or_like('file_permohonan', $q);
	$this->db->or_like('status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Jadwal_rapat_model.php */
/* Location: ./application/models/Jadwal_rapat_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-12-29 07:53:22 */
/* http://harviacode.com */
